{
 "title": "FRESCO_DashBoard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ambient and Sample Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) =>\n    r[\"_field\"] == \"Temp_amb\" or\n    r[\"_field\"] == \"Temp_S1\" or\n    r[\"_field\"] == \"Temp_S2\" or\n    r[\"_field\"] == \"Temp_S3\" or\n    r[\"_field\"] == \"Temp_S4\" or\n    r[\"_field\"] == \"Temp_Box\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Ambient and Sample Temperatures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_amb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_S1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] ==  \"Temp_S2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] ==  \"Temp_S3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_S4\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_Box\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Temperature differences Sample - Ambient",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_S1\" or r[\"_field\"] == \"Temp_amb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      ΔT_S1: r.Temp_S1 - r.Temp_amb\n  }))\n  |> keep(columns: [\"_time\", \"ΔT_S1\"])\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_S2\" or r[\"_field\"] == \"Temp_amb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      ΔT_S2: r.Temp_S2 - r.Temp_amb\n  }))\n  |> keep(columns: [\"_time\", \"ΔT_S2\"])\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_S3\" or r[\"_field\"] == \"Temp_amb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      ΔT_S3: r.Temp_S3 - r.Temp_amb\n  }))\n  |> keep(columns: [\"_time\", \"ΔT_S3\"])\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_S4\" or r[\"_field\"] == \"Temp_amb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      ΔT_S4: r.Temp_S4 - r.Temp_amb\n  }))\n  |> keep(columns: [\"_time\", \"ΔT_S4\"])\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_Box\" or r[\"_field\"] == \"Temp_amb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      ΔT_Box: r.Temp_Box - r.Temp_amb\n  }))\n  |> keep(columns: [\"_time\", \"ΔT_Box\"])\n"
    }
   ]
  },
  {
   "title": "Temperature differences Sample - Ambient",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_S1\" or r[\"_field\"] == \"Temp_amb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      ΔT_S1: r.Temp_S1 - r.Temp_amb\n  }))\n  |> keep(columns: [\"_time\", \"ΔT_S1\"])\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_S2\" or r[\"_field\"] == \"Temp_amb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      ΔT_S2: r.Temp_S2 - r.Temp_amb\n  }))\n  |> keep(columns: [\"_time\", \"ΔT_S2\"])\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_S3\" or r[\"_field\"] == \"Temp_amb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      ΔT_S3: r.Temp_S3 - r.Temp_amb\n  }))\n  |> keep(columns: [\"_time\", \"ΔT_S3\"])\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_S4\" or r[\"_field\"] == \"Temp_amb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      ΔT_S4: r.Temp_S4 - r.Temp_amb\n  }))\n  |> keep(columns: [\"_time\", \"ΔT_S4\"])\n"
    },
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_Box\" or r[\"_field\"] == \"Temp_amb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      ΔT_Box: r.Temp_Box - r.Temp_amb\n  }))\n  |> keep(columns: [\"_time\", \"ΔT_Box\"])\n"
    }
   ]
  },
  {
   "title": "Solar Irradiance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Irradiance\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "IR Sky Temp.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"IR Sky\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Ambient Temp. 1,2, and 3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_amb\" or r[\"_field\"] == \"Temp_amb 2\" or r[\"_field\"] == \"Temp_amb 3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Relative Humidity 1,2, and 3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Humidity\" or r[\"_field\"] == \"Humidity 2\" or r[\"_field\"] == \"Humidity 3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cooling Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PD1\" or r[\"_field\"] == \"PD2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cooling Power Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TPC1\" or r[\"_field\"] == \"TPC2\" or r[\"_field\"] == \"SetP\" or r[\"_field\"] == \"Temp_amb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cooling Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PD1\" or r[\"_field\"] == \"PD2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "On board temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"ESP8266\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Measurements\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temp_Board\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}